package com.interview.auth.exception;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_UNAUTHORIZED,
    AUTH_EMAIL_TAKEN,
    AUTH_EMAIL_UNVERIFIED,
    AUTH_ACCOUNT_DISABLED,
    AUTH_INVALID_EMAIL,
    AUTH_GOOGLE_UNAVAILABLE,
    AUTH_GITHUB_UNAVAILABLE,
    AUTH_USE_GOOGLE,
    USER_NOT_FOUND,
    ALREADY_PREMIUM,
    BILLING_UNAVAILABLE,
    BILLING_NOT_PAID,
    PAYMENT_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}
